DROP TABLE VNADSPRD.ICOE_EQUIPMENT_TBL PURGE

```sql
CREATE TABLE VNADSPRD.ICOE_EQUIPMENT_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.icoe_mv_logical_equipment
OPTIONS(description = 'VNADSPRD.ICOE_EQUIPMENT_TBL');
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_EQUIPMENT_TBL TO VNA_SELECT
```

```sql
CREATE TABLE VNADSPRD.ICOE_EQUIPMENT_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.icoe_mv_logical_equipment
OPTIONS(description = 'VNADSPRD.ICOE_EQUIPMENT_TBL');
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_EQUIPMENT_TBL TO VNA_SELECT
```

CREATE INDEX VNADSPRD.IDX_ICOE_EQUIP_TBL ON VNADSPRD.ICOE_EQUIPMENT_TBL(PHYSICAL_EQUIPMENT_REFERENC_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX1_ICOE_EQUIP_TBL ON VNADSPRD.ICOE_EQUIPMENT_TBL(PARENT_EQP_REFERENCE_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX2_ICOE_EQUIP_TBL ON VNADSPRD.ICOE_EQUIPMENT_TBL(SHELF_TYPE) NOLOGGING

CREATE INDEX VNADSPRD.IDX3_ICOE_EQUIP_TBL ON VNADSPRD.ICOE_EQUIPMENT_TBL(SITE_REFERENCE_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX4_ICOE_EQUIP_TBL ON VNADSPRD.ICOE_EQUIPMENT_TBL(CONTAINER) NOLOGGING

DROP TABLE VNADSPRD.ICOE_CARD_TBL PURGE

```sql
CREATE TABLE VNADSPRD.ICOE_CARD_TBL AS
SELECT * 
FROM `your_project.your_dataset.VNADSPRD`.icoe_mv_logical_card
OPTIONS(description="VNADSPRD.ICOE_CARD_TBL");
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_CARD_TBL TO `VNA_SELECT`
```

```sql
CREATE TABLE VNADSPRD.ICOE_CARD_TBL AS
SELECT * 
FROM `your_project.your_dataset.VNADSPRD`.icoe_mv_logical_card
OPTIONS(description="VNADSPRD.ICOE_CARD_TBL");
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_CARD_TBL TO `VNA_SELECT`
```

CREATE INDEX VNADSPRD.IDX_ICOE_CARD_TBL ON VNADSPRD.ICOE_CARD_TBL(CARD_REFERENCE_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX1_ICOE_CARD_TBL ON VNADSPRD.ICOE_CARD_TBL(SLOT_REFERENCE_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX2_ICOE_CARD_TBL ON VNADSPRD.ICOE_CARD_TBL(PARENT_CARD_REF_ID) NOLOGGING

DROP TABLE VNADSPRD.ICOE_SLOT_TBL PURGE

```sql
CREATE TABLE VNADSPRD.ICOE_SLOT_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.ICOE_PVNR_MV_LOGICAL_SLOT
OPTIONS(description = 'VNADSPRD.ICOE_SLOT_TBL');
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_SLOT_TBL TO VNA_SELECT
```

```sql
CREATE TABLE VNADSPRD.ICOE_SLOT_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.ICOE_PVNR_MV_LOGICAL_SLOT
OPTIONS(description = 'VNADSPRD.ICOE_SLOT_TBL');
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_SLOT_TBL TO VNA_SELECT
```

CREATE INDEX VNADSPRD.IDX_SLOT_TBL ON VNADSPRD.ICOE_SLOT_TBL(SLOT_REFERENCE_ID) NOLOGGING

DROP TABLE VNADSPRD.ICOE_SITE_TBL PURGE

```sql
CREATE TABLE VNADSPRD.ICOE_SITE_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.ICOE_MV_SITE
OPTIONS(description="VNADSPRD.ICOE_SITE_TBL");
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_SITE_TBL TO `VNA_SELECT`
```

```sql
CREATE TABLE VNADSPRD.ICOE_SITE_TBL AS
SELECT * FROM `your_project.your_dataset.VNADSPRD`.ICOE_MV_SITE
OPTIONS(description="VNADSPRD.ICOE_SITE_TBL");
```

```sql
GRANT SELECT ON `VNADSPRD`.ICOE_SITE_TBL TO `VNA_SELECT`
```

CREATE INDEX VNADSPRD.IDX_SITE_TBL ON VNADSPRD.ICOE_SITE_TBL(SITE_REFERENCE_ID) NOLOGGING

CREATE INDEX VNADSPRD.IDX1_SITE_TBL ON VNADSPRD.ICOE_SITE_TBL(CLLI) NOLOGGING

TRUNCATE TABLE vnadsprd.IEN_MR_CHANNEL_TEMP

ALTER INDEX vnadsprd.IDX1_IEN_MR_CHANNEL_TEMP UNUSABLE

ALTER INDEX vnadsprd.IDX2_IEN_MR_CHANNEL_TEMP UNUSABLE

ALTER INDEX vnadsprd.IDX1_IEN_MR_CHANNEL_TEMP REBUILD

ALTER INDEX vnadsprd.IDX2_IEN_MR_CHANNEL_TEMP REBUILD

truncate table vnadsprd.IEN_MARKET_INPUT_LIST_STG

ALTER INDEX vnadsprd.IDX1_IEN_MARKET_INPUT_LIST_STG UNUSABLE

ALTER INDEX vnadsprd.IDX2_IEN_MARKET_INPUT_LIST_STG UNUSABLE

ALTER INDEX vnadsprd.IDX3_IEN_MARKET_INPUT_LIST_STG UNUSABLE

ALTER INDEX vnadsprd.IDX1_IEN_MARKET_INPUT_LIST_STG REBUILD

ALTER INDEX vnadsprd.IDX2_IEN_MARKET_INPUT_LIST_STG REBUILD

ALTER INDEX vnadsprd.IDX3_IEN_MARKET_INPUT_LIST_STG REBUILD

truncate table vnadsprd.IEN_MARKET_INPUT_LIST_STG_TMP

TRUNCATE TABLE vnadsprd.IEN_MARKET_INPUT_LIST

ALTER INDEX vnadsprd.IEN_TRAIL_NAME_IDX UNUSABLE

ALTER INDEX VNADSPRD.IEN_TRAIL_NAME_IDX REBUILD

TRUNCATE TABLE vnadsprd.IEN_MR_CHANNEL_TEMP

```sql
INSERT INTO `your_project.your_dataset.vnadsprd`.IEN_MARKET_INPUT_LIST_STG (
  TRAIL_ID,
  TRAIL_NAME,
  STATUS,
  TYPE,
  VERSION,
  SEQUENCE,
  PORT_REFERENCE_ID,
  SOURCE,
  CHANNEL_NAME,
  SEQUENCE_NUMBER,
  PORT_STATUS,
  ELEMENT_TYPE,
  NF_ID,
  ACLLI,
  ZCLLI,
  LAST_REFRESHED_TS,
  EQUIPMENT_ID
)
SELECT DISTINCT 
  VW.TRAIL_ID,
  VW.TRAIL_NAME,
  VW.STATUS,
  VW.TYPE,
  VW.VERSION,
  TCE.SEQUENCE,
  E.ELEMENT_REF_ID AS PORT_REFERENCE_ID,
  E.SOURCE,
  E.CHANNEL_NAME,
  NULL AS SEQUENCE_NUMBER,
  NULL AS PORT_STATUS,
  E.ELEMENT_TYPE,
  VW.PROJECT_ID,
  ASITE.CLLI AS ACLLI,
  ZSITE.CLLI AS ZCLLI,
  CURRENT_TIMESTAMP(),
  NULL AS EQUIPMENT_ID
FROM 
  `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_ELEMENT E
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL VW 
  ON VW.TRAIL_ID = E.TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_COMPONENT_ELEMENT TCE 
  ON TCE.ELEMENT_ID = E.ELEMENT_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_SITE_TBL ASITE 
  ON VW.A_SITE_ID = ASITE.SITE_REFERENCE_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_SITE_TBL ZSITE 
  ON VW.Z_SITE_ID = ZSITE.SITE_REFERENCE_ID
WHERE 
  E.ELEMENT_TYPE = 'E'
  AND E.SOURCE IN ('IVAPP_PORT', 'IVAPP_LOGICAL', 'IVAPP_PANEL')

UNION ALL

SELECT 
  X.TRAIL_ID,
  X.TRAIL_NAME,
  X.STATUS,
  X.TYPE,
  X.VERSION,
  TCE.SEQUENCE,
  T.A_PORT_ID AS PORT_REFERENCE_ID,
  'NAUTILUS' AS SOURCE,
  TC.CHANNEL_NAME,
  TC.SEQUENCE_NUMBER,
  TC.STATUS AS PORT_STATUS,
  TE.ELEMENT_TYPE,
  X.PROJECT_ID,
  X.ACLLI,
  X.ZCLLI,
  CURRENT_TIMESTAMP(),
  NULL AS EQUIPMENT_ID
FROM 
  `your_project.your_dataset.vnadsprd`.NAUT_TRAIL T
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_CHANNEL TC 
  ON T.TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_COMPONENT_ELEMENT TCE 
  ON TCE.ELEMENT_ID = TC.ELEMENT_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_ELEMENT TE 
  ON TE.CHANNEL_NAME = TC.CHANNEL_NAME AND TE.PARENT_TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ien_mr_channel_temp X 
  ON T.TRAIL_ID = X.PARENT_TRAIL_ID AND TC.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS STRING)

UNION ALL

SELECT 
  X.TRAIL_ID,
  X.TRAIL_NAME,
  X.STATUS,
  X.TYPE,
  X.VERSION,
  TCE.SEQUENCE,
  T.Z_PORT_ID AS PORT_REFERENCE_ID,
  'NAUTILUS' AS SOURCE,
  TC.CHANNEL_NAME,
  TC.SEQUENCE_NUMBER,
  TC.STATUS AS PORT_STATUS,
  TE.ELEMENT_TYPE,
  X.PROJECT_ID,
  X.ACLLI,
  X.ZCLLI,
  CURRENT_TIMESTAMP(),
  NULL AS EQUIPMENT_ID
FROM 
  `your_project.your_dataset.vnadsprd`.NAUT_TRAIL T
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_CHANNEL TC 
  ON T.TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_COMPONENT_ELEMENT TCE 
  ON TCE.ELEMENT_ID = TC.ELEMENT_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_ELEMENT TE 
  ON TE.CHANNEL_NAME = TC.CHANNEL_NAME AND TE.PARENT_TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ien_mr_channel_temp X 
  ON T.TRAIL_ID = X.PARENT_TRAIL_ID AND TC.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS STRING)

UNION ALL

SELECT 
  X.TRAIL_ID,
  X.TRAIL_NAME,
  X.STATUS,
  X.TYPE,
  X.VERSION,
  TCE.SEQUENCE,
  T.A_PORT_ID_REVERSE AS PORT_REFERENCE_ID,
  'NAUTILUS' AS SOURCE,
  TC.CHANNEL_NAME,
  TC.SEQUENCE_NUMBER,
  TC.STATUS AS PORT_STATUS,
  TE.ELEMENT_TYPE,
  X.PROJECT_ID,
  X.ACLLI,
  X.ZCLLI,
  CURRENT_TIMESTAMP(),
  NULL AS EQUIPMENT_ID
FROM 
  `your_project.your_dataset.vnadsprd`.NAUT_TRAIL T
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_CHANNEL TC 
  ON T.TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_COMPONENT_ELEMENT TCE 
  ON TCE.ELEMENT_ID = TC.ELEMENT_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_ELEMENT TE 
  ON TE.CHANNEL_NAME = TC.CHANNEL_NAME AND TE.PARENT_TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ien_mr_channel_temp X 
  ON T.TRAIL_ID = X.PARENT_TRAIL_ID AND TC.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS STRING)

UNION ALL

SELECT 
  X.TRAIL_ID,
  X.TRAIL_NAME,
  X.STATUS,
  X.TYPE,
  X.VERSION,
  TCE.SEQUENCE,
  T.Z_PORT_ID_REVERSE AS PORT_REFERENCE_ID,
  'NAUTILUS' AS SOURCE,
  TC.CHANNEL_NAME,
  TC.SEQUENCE_NUMBER,
  TC.STATUS AS PORT_STATUS,
  TE.ELEMENT_TYPE,
  X.PROJECT_ID,
  X.ACLLI,
  X.ZCLLI,
  CURRENT_TIMESTAMP(),
  NULL AS EQUIPMENT_ID
FROM 
  `your_project.your_dataset.vnadsprd`.NAUT_TRAIL T
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_CHANNEL TC 
  ON T.TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_COMPONENT_ELEMENT TCE 
  ON TCE.ELEMENT_ID = TC.ELEMENT_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.NAUT_TRAIL_ELEMENT TE 
  ON TE.CHANNEL_NAME = TC.CHANNEL_NAME AND TE.PARENT_TRAIL_ID = TC.PARENT_TRAIL_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ien_mr_channel_temp X 
  ON T.TRAIL_ID = X.PARENT_TRAIL_ID AND TC.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS STRING)
```

```sql
INSERT INTO `your_project.your_dataset.vnadsprd`.IEN_MARKET_INPUT_LIST_STG_TMP 
(TRAIL_ID, TRAIL_NAME, STATUS, TYPE, VERSION, SEQUENCE, PORT_REFERENCE_ID, SOURCE, CHANNEL_NAME, SEQUENCE_NUMBER, PORT_STATUS, ELEMENT_TYPE, NF_ID, ACLLI, ZCLLI, LAST_REFRESHED_TS, EQUIPMENT_ID)
SELECT DISTINCT 
    VW.TRAIL_ID,
    VW.TRAIL_NAME,
    VW.STATUS,
    VW.TYPE,
    VW.VERSION,
    TCE.SEQUENCE,
    NULL AS PORT_REFERENCE_ID,
    E.SOURCE,
    VW.A_PORT_AID AS CHANNEL_NAME,
    NULL AS SEQUENCE_NUMBER,
    VW.STATUS AS PORT_STATUS,
    E.ELEMENT_TYPE,
    VW.PROJECT_ID AS NF_ID,
    ASITE.CLLI AS ACLLI,
    ZSITE.CLLI AS ZCLLI,
    TIMESTAMP(CURRENT_TIMESTAMP()),
    VW.A_EQUIPMENT_ID AS EQUIPMENT_ID
FROM 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_ELEMENT E
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_TMP VW ON VW.TRAIL_ID = E.TRAIL_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_COMPONENT_ELEMENT TCE ON TCE.ELEMENT_ID = E.ELEMENT_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.ICOE_SITE_TBL ASITE ON VW.A_SITE_ID = ASITE.SITE_REFERENCE_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.ICOE_SITE_TBL ZSITE ON VW.Z_SITE_ID = ZSITE.SITE_REFERENCE_ID
WHERE 
    E.ELEMENT_TYPE = 'K'
    AND UPPER(VW.TYPE) LIKE '%LAG%'
UNION ALL
SELECT DISTINCT 
    VW.TRAIL_ID,
    VW.TRAIL_NAME,
    VW.STATUS,
    VW.TYPE,
    VW.VERSION,
    TCE.SEQUENCE,
    NULL AS PORT_REFERENCE_ID,
    E.SOURCE,
    VW.Z_PORT_AID AS CHANNEL_NAME,
    NULL AS SEQUENCE_NUMBER,
    VW.STATUS AS PORT_STATUS,
    E.ELEMENT_TYPE,
    VW.PROJECT_ID AS NF_ID,
    ASITE.CLLI AS ACLLI,
    ZSITE.CLLI AS ZCLLI,
    TIMESTAMP(CURRENT_TIMESTAMP()),
    VW.Z_EQUIPMENT_ID AS EQUIPMENT_ID
FROM 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_ELEMENT E
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_TMP VW ON VW.TRAIL_ID = E.TRAIL_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.NAUT_TRAIL_COMPONENT_ELEMENT TCE ON TCE.ELEMENT_ID = E.ELEMENT_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.ICOE_SITE_TBL ASITE ON VW.A_SITE_ID = ASITE.SITE_REFERENCE_ID
INNER JOIN 
    `your_project.your_dataset.VNADSPRD`.ICOE_SITE_TBL ZSITE ON VW.Z_SITE_ID = ZSITE.SITE_REFERENCE_ID
WHERE 
    E.ELEMENT_TYPE = 'K'
    AND UPPER(VW.TYPE) LIKE '%LAG%';
```

```sql
INSERT INTO `your_project.your_dataset.VNADSPRD`.IEN_MARKET_INPUT_LIST (
  TRAIL_ID,
  MARKET_NAME,
  MARKET_STATE,
  CLLI,
  TRAIL_NAME,
  TID_LOGICAL,
  ALTERNATE_NAME,
  NFID,
  CREATED_TS
)
SELECT DISTINCT
  TRAIL_ID,
  IF(market.VZB_MARKET_CITY_OR_VZT_REGION IS NULL, 'Not Available', market.VZB_MARKET_CITY_OR_VZT_REGION) AS market_name,
  CASE 
    WHEN market.STATE IS NOT NULL THEN market.STATE
    ELSE IF(S.CLLI IS NULL, 'N/A', SUBSTR(S.CLLI, 5, 2))
  END AS market_area,
  IF(S.CLLI IS NULL, 'N/A', S.CLLI) AS EQUIP_CLLI,
  G.TRAIL_NAME AS TRAIL_NAME,
  CASE 
    WHEN E.SHELF_TYPE = 'MSERI' THEN MSE.TID_LOGICAL
    ELSE E.TID_LOGICAL
  END AS TID_LOGICAL,
  CASE 
    WHEN E.SHELF_TYPE = 'MSERI' THEN MSE.ALTERNATE_NAME
    ELSE E.ALTERNATE_NAME
  END AS ALTERNATE_NAME,
  IF(G.NF_ID IS NULL, 'N/A', G.NF_ID) AS NF_ID,
  CURRENT_TIMESTAMP()
FROM 
  `your_project.your_dataset.vnadsprd`.IEN_MARKET_INPUT_LIST_STG G
  INNER JOIN `your_project.your_dataset.vnadsprd`.icoe_pvnr_t_logical_port P 
    ON G.PORT_REFERENCE_ID = P.PORT_REFERENCE_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_EQUIPMENT_TBL E 
    ON P.EQP_REFERENCE_ID = E.EQP_REFERENCE_ID
  LEFT JOIN `your_project.your_dataset.vnadsprd`.ICOE_EQUIPMENT_TBL MSE 
    ON E.PHYSICAL_EQUIPMENT_REFERENC_ID = MSE.EQP_REFERENCE_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_SITE_TBL S 
    ON E.SITE_REFERENCE_ID = S.SITE_REFERENCE_ID
  LEFT JOIN `your_project.your_dataset.vnadsprd`.IEN_UT_PMO_TRACKER MARKET 
    ON MARKET.SITE_CLLI = S.CLLI
WHERE 
  G.element_type <> 'K';
```

```sql
INSERT INTO `your_project.your_dataset.VNADSPRD`.IEN_MARKET_INPUT_LIST (
  TRAIL_ID,
  MARKET_NAME,
  MARKET_STATE,
  CLLI,
  TRAIL_NAME,
  TID_LOGICAL,
  ALTERNATE_NAME,
  NFID,
  CREATED_TS
)
SELECT DISTINCT
  TRAIL_ID,
  IF(market.VZB_MARKET_CITY_OR_VZT_REGION IS NULL, 'Not Available', market.VZB_MARKET_CITY_OR_VZT_REGION) AS market_name,
  CASE 
    WHEN market.STATE IS NOT NULL THEN market.STATE
    ELSE IF(S.CLLI IS NULL, 'N/A', SUBSTR(S.CLLI, 5, 2))
  END AS market_area,
  IF(S.CLLI IS NULL, 'N/A', S.CLLI) AS EQUIP_CLLI,
  G.TRAIL_NAME AS TRAIL_NAME,
  CASE 
    WHEN E.SHELF_TYPE = 'MSERI' THEN MSE.TID_LOGICAL
    ELSE E.TID_LOGICAL
  END AS TID_LOGICAL,
  CASE 
    WHEN E.SHELF_TYPE = 'MSERI' THEN MSE.ALTERNATE_NAME
    ELSE E.ALTERNATE_NAME
  END AS ALTERNATE_NAME,
  IF(G.NF_ID IS NULL, 'N/A', G.NF_ID) AS NF_ID,
  CURRENT_TIMESTAMP()
FROM 
  `your_project.your_dataset.vnadsprd`.IEN_MARKET_INPUT_LIST_STG_TMP G
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_EQUIPMENT_TBL E 
    ON E.EQP_REFERENCE_ID = G.EQUIPMENT_ID
  LEFT JOIN `your_project.your_dataset.vnadsprd`.ICOE_EQUIPMENT_TBL MSE 
    ON E.PHYSICAL_EQUIPMENT_REFERENC_ID = MSE.EQP_REFERENCE_ID
  INNER JOIN `your_project.your_dataset.vnadsprd`.ICOE_SITE_TBL S 
    ON E.SITE_REFERENCE_ID = S.SITE_REFERENCE_ID
  LEFT JOIN `your_project.your_dataset.vnadsprd`.IEN_UT_PMO_TRACKER MARKET 
    ON MARKET.SITE_CLLI = S.CLLI
WHERE 
  G.element_type = 'K';
```

