BEGIN

-- Step 1
DELETE FROM `vnadsprd.ien_market_input_list_stg` WHERE TRUE;

-- Step 2
INSERT INTO `vnadsprd.ien_market_input_list_stg`
SELECT 
  X.TRAIL_ID, 
  X.TRAIL_NAME, 
  X.STATUS, 
  X.TYPE, 
  X.VERSION, 
  TCE.SEQUENCE, 
  T.Z_PORT_ID_REVERSE AS PORT_REFERENCE_ID, 
  'NAUTILUS' AS SOURCE, 
  TC.CHANNEL_NAME, 
  TC.SEQUENCE_NUMBER, 
  TC.STATUS AS PORT_STATUS, 
  TE.ELEMENT_TYPE, 
  X.PROJECT_ID, 
  X.ACLLI, 
  X.ZCLLI, 
  CURRENT_TIMESTAMP() 
FROM 
  (SELECT 
     VW.TRAIL_ID, 
     VW.TRAIL_NAME, 
     VW.TYPE, 
     VW.STATUS, 
     VW.VERSION, 
     PARENT_TRAIL_ID, 
     MIN((CHANNEL_NAME)) AS CHANNEL_NAME, 
     VW.PROJECT_ID, 
     ASITE.CLLI AS ACLLI, 
     ZSITE.CLLI AS ZCLLI 
   FROM 
     vnadsprd.NAUT_TRAIL_ELEMENT AS TE 
   JOIN 
     vnadsprd.NAUT_TRAIL AS VW ON VW.TRAIL_ID = TE.TRAIL_ID 
   JOIN 
     vnadsprd.ICOE_SITE_TBL AS ASITE ON VW.A_SITE_ID = ASITE.SITE_REFERENCE_ID 
   JOIN 
     vnadsprd.ICOE_SITE_TBL AS ZSITE ON VW.Z_SITE_ID = ZSITE.SITE_REFERENCE_ID 
   WHERE 
     TE.ELEMENT_TYPE = 'P' 
   GROUP BY 
     VW.TRAIL_ID, 
     VW.TRAIL_NAME, 
     VW.TYPE, 
     VW.STATUS, 
     VW.VERSION, 
     TE.PARENT_TRAIL_ID, 
     VW.PROJECT_ID, 
     ASITE.CLLI, 
     ZSITE.CLLI) AS X 
JOIN 
  vnadsprd.NAUT_TRAIL AS T ON T.TRAIL_ID = X.PARENT_TRAIL_ID 
JOIN 
  vnadsprd.NAUT_TRAIL_CHANNEL AS TC ON TC.PARENT_TRAIL_ID = X.PARENT_TRAIL_ID AND TC.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS TEXT) 
JOIN 
  vnadsprd.NAUT_TRAIL_ELEMENT AS TE ON TE.PARENT_TRAIL_ID = X.PARENT_TRAIL_ID AND TE.CHANNEL_NAME = CAST(X.CHANNEL_NAME AS TEXT) 
JOIN 
  vnadsprd.NAUT_TRAIL_COMPONENT_ELEMENT AS TCE ON TCE.ELEMENT_ID = TE.ELEMENT_ID;


-- Step 3
DELETE FROM `vnadsprd.ien_market_input_list` WHERE TRUE;

-- Step 4
INSERT INTO `vnadsprd.ien_market_input_list`
SELECT DISTINCT 
  TRAIL_ID, 
  IFNULL(market.VZB_MARKET_CITY_OR_VZT_REGION, 'NOT Available') AS market_name, 
  CASE WHEN market.STATE IS NOT NULL THEN market.STATE ELSE IFNULL(SUBSTR(S.CLLI, 5, 2), 'N/A') END AS market_area, 
  IFNULL(S.CLLI, 'N/A') AS EQUIP_CLLI, 
  G.TRAIL_NAME AS TRAIL_NAME, 
  (CASE WHEN (E.SHELF_TYPE = 'MSERI') THEN MSE.TID_LOGICAL ELSE E.TID_LOGICAL END) AS TID_LOGICAL, 
  (CASE WHEN (E.SHELF_TYPE = 'MSERI') THEN MSE.ALTERNATE_NAME ELSE E.ALTERNATE_NAME END) AS ALTERNATE_NAME, 
  IFNULL(G.NF_ID, 'N/A') AS NF_ID, 
  CURRENT_TIMESTAMP() 
FROM 
  (((((vnadsprd.IEN_MARKET_INPUT_LIST_STG AS G 
  JOIN vnadsprd.icoe_pvnr_t_logical_port AS P ON (P.PORT_REFERENCE_ID = G.PORT_REFERENCE_ID)) 
  JOIN vnadsprd.ICOE_EQUIPMENT_TBL AS E ON (P.EQP_REFERENCE_ID = E.EQP_REFERENCE_ID)) 
  LEFT JOIN vnadsprd.ICOE_EQUIPMENT_TBL AS MSE ON (E.PHYSICAL_EQUIPMENT_REFERENC_ID = MSE.EQP_REFERENCE_ID)) 
  JOIN vnadsprd.ICOE_SITE_TBL AS S ON (E.SITE_REFERENCE_ID = S.SITE_REFERENCE_ID)) 
  LEFT JOIN vnadsprd.IEN_UT_PMO_TRACKER AS market ON (market.SITE_CLLI = S.CLLI);


END;