TRUNCATE TABLE DEMO_MARKET_STG

```sql
INSERT INTO `your_project.your_dataset.DEMO_MARKET_STG` (
  PROJECT_ID,
  SITE_CODE,
  REGION,
  DEVICE_TYPE,
  PORT_NUMBER,
  CHANNEL_ID,
  CREATED_DATE
)

SELECT DISTINCT
  SRC.PROJECT_ID,
  SITE.SITE_CODE,
  SITE.REGION,
  DEV.DEVICE_TYPE,
  DEV.PORT_NUMBER,
  DEV.CHANNEL_ID,
  CURRENT_TIMESTAMP

FROM `your_project.your_dataset.DEMO_PROJECTS` SRC
INNER JOIN `your_project.your_dataset.DEMO_SITES` SITE
  ON SRC.SITE_ID = SITE.SITE_ID
LEFT JOIN `your_project.your_dataset.DEMO_DEVICES` DEV
  ON SITE.SITE_ID = DEV.SITE_ID

WHERE SRC.STATUS = 'ACTIVE';
```

